### ISSUE TITLE
Unable to Share Calendar on iOS

### ISSUE THREAD

**Issue by blunweon** [ckulka/baikal-docker#207]
Hey there,

I love your work for supporting a docker image of baikal.

Currently, I have it running via a Dockge LXC on my Proxmox server and I encountered this issue where I am unable to add people to my calendar through the iOS calendar app. I am able to add the CalDAV and CardDAV to my own iOS devices, but I am unable to add people to the calendars for viewing/editing.

This is my docker compose as per the template and some searching for the different arguments:

```
version: "2"
services:
  baikal:
    image: ckulka/baikal:nginx
    environment:
      MSMTPRC: |
        defaults
        port         "587"
        tls          "on"
        tls_starttls "on"
        account      "smtp2go"
        host         "mail.smtp2go.com"
        from         "<redacted>"
        auth         "on"
        user         "<redacted>"
        password     "<redacted>"
        account default : smtp2go
    restart: always
    ports:
      - 81:80
    volumes:
      - ./config:/var/www/baikal/config
      - ./Specific:/var/www/baikal/Specific
networks: {}
```

I hoped that this worked to send out emails or anything, but there seemed to not be any emails being sent out despite the configuration being somewhat correct(?).

This is the issue that spits out on the WebGUI which states `<cs:invite-invalid>` and `<d:invite-invalid>` for some reason (with particulars redacted):
![floorp_tqjdZHZBTR](https://github.com/ckulka/baikal-docker/assets/169746148/3a801e78-5804-4d9e-98ae-9edc448c9a2c)

I would love to be pointed in the right direction for getting this solved so I can add people to my calendars on iOS, though it might just be user-error.

**Comment by ckulka** [comment]
Hi @blunweon ,

Do you know if the email configuration works?

If you are unsure, you can

1. Copy [cypress/fixtures/mail-test.php](https://github.com/ckulka/baikal-docker/blob/master/cypress/fixtures/mail-test.php) I used for the tests into your container under `/var/www/baikal/html`
2. Modify the email recipient to your own email address
3. Invoke the PHP file and verify the email arrives
4. Remove the test file again, so that others cannot spam you with emails from your own server

**Comment by ckulka** [comment]
Hi @blunweon , sorry for the delay! If the email is sent out with the test file, then I'm afraid that it's most likely something with Baikal itself, I'd open an issue over at https://github.com/sabre-io/Baikal/issues.

Since the emails arrive in your inbox if they are sent from your container, I'd imagine Baikal doesn't even get to the point where the invitations are being sent, but errors out beforehand.
