### ISSUE TITLE
Please update to 0.7.2

### ISSUE THREAD

**Issue by Schnuecks** [ckulka/baikal-docker#27]

**Comment by ckulka** [comment]
Hi @Schnuecks ,

just pushed an update for version 0.7.2 and Docker Hub is building it now. Should be there in maybe 6 hours, just takes a little  until all 12 images are published (roughly 30 minutes per image on Docker Hub).

Since I don't have a Baikal instance running anymore and can do only very limited testing, can you please let me know if the new image works for you?

**Comment by Schnuecks** [comment]
Hi, thank you. I will test it and report back.

**Comment by Schnuecks** [comment]
Hi, after update this error occours.
Composer detected issues in your platform: Your Composer dependencies require the following PHP extensions to be installed: curl

**Comment by ckulka** [comment]
Hi @Schnuecks ,

thanks for testing so quickly - I added the missing dependency, it's building now again. Based on the last release, it'll take 3h until all images are published.

When did you get the error? Unfortunately I didn't see that when I started the container with the new version, but want to make it doesn't happen in the other image variant (not sure if you use Apache httpd or Nginx).

**Comment by Schnuecks** [comment]
Hi, i got the error when i visit the page directly after update with the nginx version.
But now it seems to work, the update wizard starts and upgrade the db to 0.7.2.
At the moment it seems to work so far. If anything happens i report back.
thanks again.
