### ISSUE TITLE
Container log file

### ISSUE THREAD

**Issue by Glareascum** [ckulka/baikal-docker#53]
Is it possible to specify a custom log file location? I'd like to put baikal under the eye of fail2ban, so I need a log to scan and apply some rules to avoid brute force attacks.

**Comment by ckulka** [comment]
Hi @Glareascum , do you use Nginx or Apache and can you use the container logs, or do you need the actual access log files?

Assuming fail2ban can not consume container logs out of the box, I can think of three solutions:

### Consume container JSON log files

The access log is printed to the container logs, are stored in `/var/lib/docker/containers/<container id>/<container id>-json.log` unless you changed your logging driver, e.g. to journald (something I would personally actually recommend, it helps with disk space filling up with log files).

The container id changes every time you start a new one, so I don't know if you can just consume all container logs and filter in fail2ban, or if fail2ban has an overall better way of consuming Docker container logs.

### Mount log folder

If you don't need the access log in the container logs, I would mount `/var/log/apache2` or `/var/log/nginx` to a local folder and then consume log files from there. It's the simplest solution, but since the logs are no longer sent to stdout and stderr, your container logs will now be empty - which might be acceptable for you though.

### Log to multiple files

If you want to keep the container logs and additionally output access logs to a separate file, you need to do the following:

1. Copy the `/etc/nginx/nginx.conf` contents to a new local file
2. Add an additional `access_log` directive underneath the existing one
3. Mount the additional logging folder into the container
4. Mount the customised `nginx.conf` file into the container

On Apache you might get away with mounting a new configuration file in `/etc/apache2/conf-enabled` with the the following line combined with step 3:

```
CustomLog /var/log/apache-custom/access.log vhost_combined
```

Does this help?
