### ISSUE TITLE
Can't start container

### ISSUE THREAD

**Issue by andreyp1986** [ckulka/baikal-docker#6]
Trying to load latest container:
Digest: sha256:3a571f324835b9804fb8a234033dee3778b4b28a146f7b2b6a56fffac963446d
Status: Downloaded newer image for ckulka/baikal:latest

I get this message:
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
[Wed Apr 04 15:05:46.099473 2018] [ssl:warn] [pid 1] AH01906: 172.17.0.3:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Wed Apr 04 15:05:46.099609 2018] [ssl:warn] [pid 1] AH01909: 172.17.0.3:443:0 server certificate does NOT include an ID which matches the server name
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
[Wed Apr 04 15:05:46.134492 2018] [ssl:warn] [pid 1] AH01906: 172.17.0.3:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Wed Apr 04 15:05:46.134525 2018] [ssl:warn] [pid 1] AH01909: 172.17.0.3:443:0 server certificate does NOT include an ID which matches the server name
[Wed Apr 04 15:05:46.137362 2018] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.25 (Debian) PHP/7.2.3 OpenSSL/1.0.2l configured -- resuming normal operations
[Wed Apr 04 15:05:46.137395 2018] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Wed Apr 04 15:05:47.202687 2018] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully

**Comment by ckulka** [comment]
Hi @andreyp1986 , sorry, had my notifications turned off.

Those are "only" warnings because `ServerName` is not set in the config, as this depends on your domain, e.g. https://dav.example.com.

For more details, see https://wiki.apache.org/httpd/CommonMisconfigurations#Not_setting_a_ServerName_in_a_virtual_host.

I'll see if I switch to Nginx or insert the server name dynamically based on an environment variable.

If you already found a solution, I'm always happy about PRs :-)

**Comment by ckulka** [comment]
As far as the other warnings go, that's due to the self-signed SSL certificates, unfortunately nothing I can fix (apart from removed HTTPS support).

I'll see if I can add an example for [Let's Encrypt](https://letsencrypt.org/) with [Traefik](https://traefik.io/), since that's what I'm doing on my server anyway.

**Comment by ckulka** [comment]
39af7e8e3b634de29a5ba9bbf1e782a59452e4ff fixes the `ServerName` and `ServerAlias` warnings, I plan to release it with the next release of Baikal ... which hopefully is soon given their latest commit to fix sabre-io/Baikal#717.

**Comment by ckulka** [comment]
Now with the re-release of 0.4.6 for multi-arch (amd64 and arm32v7) to support Raspberry Pi, etc., the fix is now also available. I've also added more docs to make the transition to Traefik/Nginx easier, since it's (imho) the better solution.

I'll close the issue, but feel free to continue to add to this issue or open a new one as new details come up.

/closed
