### ISSUE TITLE
macos cant sync calendar

### ISSUE THREAD

**Issue by Ghost108** [ckulka/baikal-docker#88]
Hi all!

I installed the web version of baikal.
I created a .htaccess File in the root folder 
<img width="333" alt="Bildschirmfoto 2022-05-01 um 13 10 07" src="https://user-images.githubusercontent.com/17011498/166143404-199b0d48-371a-40d6-b9c2-71414dc2d4b9.png">

with this rules:
```
RewriteEngine On
RedirectMatch 301 ^/.well-known/caldav /html/cal.php
RedirectMatch 301 ^/.well-known/carddav /html/card.php
```

only ather this "modification" macOS is able to found and sync the calendar.

Now I would like to use your docker version - with the same macOS issue - but this time, I have no idea how can I fix it like above.
Can you help me please? Thanks a lot

**Comment by panzer-arc** [comment]
Looking around in portainer, that file appears to be in /var/lib/docker/volumes/baikal_config/_data. You could try editing it there.

**Comment by ckulka** [comment]
Hi @Ghost108 ,

the Nginx and Apache httpd configuration files should already take care of this - do you have any issues when you used the Docker images?

Example configuration files used in version 0.9.2:

* <https://github.com/ckulka/baikal-docker/blob/0.9.2/files/apache.conf>
* <https://github.com/ckulka/baikal-docker/blob/0.9.2/files/apache.conf>

**Comment by nillebor** [comment]
> Hi @Ghost108 ,
> 
> the Nginx and Apache httpd configuration files should already take care of this - do you have any issues when you used the Docker images?
> 
> Example configuration files used in version 0.9.2:
> 
>     * https://github.com/ckulka/baikal-docker/blob/0.9.2/files/apache.conf
> 
>     * https://github.com/ckulka/baikal-docker/blob/0.9.2/files/**apache.conf**

You mean?:
- https://github.com/ckulka/baikal-docker/blob/0.9.2/files/apache.conf
- https://github.com/ckulka/baikal-docker/blob/0.9.2/files/nginx.conf

**Comment by nillebor** [comment]
For better understand please see: https://lisanet.de/baikal-kontake-und-kalender-auf-eigenem-webspace/

it particularly affected macOS devices. with IOS, the error is compensated and it works. No error occurs on Android and Windows.

Can you create an Apple version of Baikal Docker?

**Comment by ckulka** [comment]
Thanks @nillebor for confirming.

Hi @Ghost108, the short answer is: it's not needed, as the root folder isn't accessible or served to browsers.

That redirect is not needed with the Docker image as the root folder is not (and should not) be accessible from the internet, only the contents inside the `html` folder should be.

That redirect and `.htaccess` file in the root folder might be required on some webhoster where you cannot configure which folders are and aren't served to browsers, they might just give you a root folder and everything within it will be served to browsers.

But since that's not the case with this Docker image (since it only serves the contents of the `html` folder to browsers), this `.htaccess` file isn't required.

I'll close this issue, but let me know if there is something unanswered 👍
