### ISSUE TITLE
Exception when editing a user's calendar

### ISSUE THREAD

**Issue by MichiFr** [ckulka/baikal-docker#90]
Using baikal 0.9.2 and when executing the calender button to edit a user's calender I often see the error message below, in Firefox.
Using menu "Users and resources" -> Button Calendars -> select one of the user's calendars.

`ErrorException: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/baikal/Core/Frameworks/Formal/Element/Text.php:69
Stack trace:
#0 [internal function]: Baikal\Framework::exception_error_handler(8192, 'htmlspecialchar...', '/var/www/baikal...', 69)
#1 /var/www/baikal/Core/Frameworks/Formal/Element/Text.php(69): htmlspecialchars(NULL)
#2 /var/www/baikal/Core/Frameworks/Formal/Form.php(354): Formal\Element\Text->render()
#3 /var/www/baikal/Core/Frameworks/BaikalAdmin/Controller/User/Calendars.php(82): Formal\Form->render()
#4 /var/www/baikal/Core/Frameworks/Flake/Core/Render/Container.php(69): BaikalAdmin\Controller\User\Calendars->render()
#5 /var/www/baikal/Core/Frameworks/Flake/Controller/Page.php(90): Flake\Core\Render\Container->renderBlocks()
#6 /var/www/baikal/html/admin/index.php(90): Flake\Controller\Page->render()
#7 {main}`

This happens with various calenders but not every time when editing the same calendar.

So no special characters are used in token ID, nor in display name not in description just plain ASCII.

I noticed, too, once this error appears I get this error on any of those calenders (from the same user). 
When leaving the webpage, and start over I can replicate that obviously a single calender may confuse baikal.

So right now I'm clueless what happens here. I've update from version 0.8.2 previously and btw, the calendar items from this and any other calendars are available with any issue.

**Comment by MichiFr** [comment]
Additional information: guess I know the source of the issue. Each calendar that does not have a description, causes this issue.

Will it be save to add one using e.g. phpMyAdmin? I'm running baikal with MariaDB/MySQL, btw.

**Comment by ckulka** [comment]
Hi @MichiFr, can you try the PHP 8.0 image variants, e.g. `ckulka/baikal:0.9.2-php8.0`?

I think it's because of a deprecation that happened in PHP 8.1 which ([despite semver conventions](https://semver.org/)) broke Baikal in a couple of places. The maintainers of Baikal addressed most of those issues when they made it PHP 8.1-ready in [release 0.9.0](https://github.com/sabre-io/Baikal/releases/tag/0.9.0), but occasionally new PHP 8.1 compatibility issues appear.

If using the PHP 8.0 image variant fixes this issue, then please contiue it for now and open an issue + stacktrace over at [sabre-io/Baikal](https://github.com/sabre-io/Baikal) so that they can fix it in the Baikal source code.

**Comment by ckulka** [comment]
Closing given this can only be fixed in the Baikal repository.
