### ISSUE TITLE
docker-compose.ssl.yaml - Not Working

### ISSUE THREAD

**Issue by patg84** [ckulka/baikal-docker#92]
Hello. Can someone please check this? I keep getting a 404 when trying to run this container. I have tried to fix it but I'm drawing a blank.

Due to change in OneCalendar for Android and iOS, I need to be able to provide an HTTPS link for those clients to keep Baikal running in a production environment. Baikal offers two different authentication methods for connecting to the service. Basic and Digest. Digest is deprecated from what I understand, and if you use Basic Auth it must flow over HTTPS. You can disable HTTPS and certificate checking in OneCalendar but I really don't want to have to explain to users to change another setting to make this already complicated thing work.

**Comment by antiftw** [comment]
I have the same issue. Have followed the instructions in the file:

- Adjust the host (it is on line 16, instead of on the mentioned 14 though)
- Create /etc/ssl/private/acme.json
- Start the stack: docker-compose -f docker-compose.ssl.yaml up

Then go to the host that I just defined in the file, which is defined in my DNS records (dav.xxxxxx.tld). But the browser keeps giving me a 404. I do not see any obvious errors in the logfiles and do see the requests coming in when I try to reach the page:

```
examples-baikal-1   | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
examples-baikal-1   | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
examples-baikal-1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
examples-traefik-1  | time="2023-08-17T08:37:19Z" level=info msg="Configuration loaded from flags."
examples-baikal-1   | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
examples-baikal-1   | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
examples-baikal-1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
examples-baikal-1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
examples-baikal-1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/40-disable-nginx-ipv6-if-unsupported.sh
examples-baikal-1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/40-fix-baikal-permissions.sh
examples-baikal-1   | 40-fix-baikal-permissions.sh: info: Adjusting Baikal file permissions for nginx
examples-traefik-1  | 192.168.2.254 - - [17/Aug/2023:08:37:28 +0000] "GET /admin/install/ HTTP/1.1" 301 17 "-" "-" 1 "web-to-websecure@internal" "-" 0ms
examples-traefik-1  | 192.168.2.254 - - [17/Aug/2023:08:37:31 +0000] "GET /admin/install/ HTTP/2.0" - - "-" "-" 2 "-" "-" 0ms
examples-traefik-1  | 192.168.2.254 - - [17/Aug/2023:08:37:32 +0000] "GET /favicon.ico HTTP/2.0" - - "-" "-" 3 "-" "-" 0ms
examples-traefik-1  | 192.168.2.254 - - [17/Aug/2023:08:37:37 +0000] "GET / HTTP/1.1" 301 17 "-" "-" 4 "web-to-websecure@internal" "-" 0ms
examples-traefik-1  | 192.168.128.1 - - [17/Aug/2023:08:37:40 +0000] "GET / HTTP/2.0" - - "-" "-" 5 "-" "-" 0ms
examples-traefik-1  | 192.168.128.1 - - [17/Aug/2023:08:37:40 +0000] "GET /favicon.ico HTTP/2.0" - - "-" "-" 6 "-" "-" 0ms
examples-baikal-1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/40-php-fpm.sh
examples-baikal-1   | 40-php-fpm.sh: info: Starting PHP 8.1
examples-baikal-1   | /docker-entrypoint.sh: Configuration complete; ready for start up
examples-baikal-1   | 2023/08/17 08:37:41 [notice] 1#1: using the "epoll" event method
examples-baikal-1   | 2023/08/17 08:37:41 [notice] 1#1: nginx/1.23.2
examples-baikal-1   | 2023/08/17 08:37:41 [notice] 1#1: built by gcc 10.2.1 20210110 (Debian 10.2.1-6) 
examples-baikal-1   | 2023/08/17 08:37:41 [notice] 1#1: OS: Linux 6.1.21-v8+
examples-baikal-1   | 2023/08/17 08:37:41 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
examples-baikal-1   | 2023/08/17 08:37:41 [notice] 1#1: start worker processes
examples-baikal-1   | 2023/08/17 08:37:41 [notice] 1#1: start worker process 47
examples-baikal-1   | 2023/08/17 08:37:41 [notice] 1#1: start worker process 48
examples-baikal-1   | 2023/08/17 08:37:41 [notice] 1#1: start worker process 49
examples-baikal-1   | 2023/08/17 08:37:41 [notice] 1#1: start worker process 50
examples-traefik-1  | 192.168.128.1 - - [17/Aug/2023:08:37:43 +0000] "GET / HTTP/2.0" - - "-" "-" 8 "-" "-" 0ms
examples-traefik-1  | 192.168.128.1 - - [17/Aug/2023:08:38:43 +0000] "GET / HTTP/2.0" - - "-" "-" 9 "-" "-" 0ms
```

To try and find out if it might be something with my setup I also tried other ways described in this project to get something to work, and that seems to work without issues. Both of the following give me a reachable Baikal admin panel:

- docker run --rm -it -p 80:80 ckulka/baikal:nginx
- docker compose up using the default `examples/docker-compose.yaml` file 

To see if there were any issues regarding the SSL and/or Traefik part of the process, I have also tried using this [acme-tls example](https://doc.traefik.io/traefik/user-guides/docker-compose/acme-tls/) from the Traefik site. Which gives me a working whois with a valid certificate.

I did notice that the `docker-compose.ssl.yaml` file has not been updated in two years, so should I assume that the contents in this file might be outdated and/or not correct anymore or has the functionality of this been verified recently?

Any help with this would be greatly appreciated.
