### ISSUE TITLE
Plugin install

### ISSUE THREAD

**Issue by zsamiatt** [ckulka/baikal-docker#97]
Hello,
How can I install plugin to baikal docker?

[https://sabre.io/dav/ics-export-plugin/](url)

**Comment by ckulka** [comment]
Hi @zsamiatt , I found instructions for another plugin ([Aerex/baikal-storage-plugin/README.md](https://github.com/Aerex/baikal-storage-plugin/blob/67e34e52b82508efff006f8fbbd0326c33af1794/README.md)) which say that those setup lines should be added to the `/var/www/baikal/Core/Frameworks/Baikal/Core/Server.php` file.

In order to use this in the Dockerfile, you'll need to modify the `Server.php` file that comes with the Docker image. There are two ways of doing so:

1. Mount a modified `Server.php` file into the container, overriding the one that's in the container
2. Dynamically update the `Server.php` file in the container when the container starts

I'm not too familiar with PHP, so that my advice with care: I'd do option 2 as you don't have to make any additional work when you upgrade Baikal later to a newer version, plus it's a little less overall effort. Below I'll describe how to do option 2, but if you'd like to use option 1 and don't know how to, let me know.

You can achieve option 2 by creating a shell script that will run when the container starts which will add the setup code to the `Server.php` file:

1. Create a shell script file `50-add-ics-export-plugin.sh` file

   ```php
   cat <<EOT >> /var/www/baikal/Core/Frameworks/Baikal/Core/Server.php
   $icsPlugin = new \Sabre\CalDAV\ICSExportPlugin();
   $server->addPlugin($icsPlugin);
   EOT
   ```
2. Mount this file into the container as `/docker-entrypoint.d/50-add-ics-export-plugin.sh`

I don't know how you run Baikal, i.e. straight from the command line with `docker run`, with Docker Compose, Kubernetes, K3s, or something else - let me know and I can also help you with mounting it.

Hope this helps 👍

**Comment by zsamiatt** [comment]
> Hi @zsamiatt , I found instructions for another plugin ([Aerex/baikal-storage-plugin/README.md](https://github.com/Aerex/baikal-storage-plugin/blob/67e34e52b82508efff006f8fbbd0326c33af1794/README.md)) which say that those setup lines should be added to the `/var/www/baikal/Core/Frameworks/Baikal/Core/Server.php` file.
> 
> In order to use this in the Dockerfile, you'll need to modify the `Server.php` file that comes with the Docker image. There are two ways of doing so:
> 
>     1. Mount a modified `Server.php` file into the container, overriding the one that's in the container
> 
>     2. Dynamically update the `Server.php` file in the container when the container starts
> 
> 
> I'm not too familiar with PHP, so that my advice with care: I'd do option 2 as you don't have to make any additional work when you upgrade Baikal later to a newer version, plus it's a little less overall effort. Below I'll describe how to do option 2, but if you'd like to use option 1 and don't know how to, let me know.
> 
> You can achieve option 2 by creating a shell script that will run when the container starts which will add the setup code to the `Server.php` file:
> 
>     1. Create a shell script file `50-add-ics-export-plugin.sh` file
>        ```
>        cat <<EOT >> /var/www/baikal/Core/Frameworks/Baikal/Core/Server.php
>        
>        // Activate iCalendar Export Plugin
>        \$icsPlugin = new \Sabre\CalDAV\ICSExportPlugin();
>        \$server->addPlugin($icsPlugin);
>        EOT
>        ```
> 
>     2. Mount this file into the container as `/docker-entrypoint.d/50-add-ics-export-plugin.sh`
> 
> 
> I don't know how you run Baikal, i.e. straight from the command line with `docker run`, with Docker Compose, Kubernetes, K3s, or something else - let me know and I can also help you with mounting it.
> 
> Hope this helps 👍

Hello I find solutions:
Thank you your help.

[https://github.com/eyalcha/baikal-docker](url)
